# Generated by Django 5.2 on 2026-08-18 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('term', 'ترم'), ('monthly', 'شهري'), ('daily', 'يومي')], max_length=10, verbose_name='نوع الاشتراك')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('payment_pending', 'بانتظار الدفع'), ('payment_submitted', 'تم رفع إثبات الدفع'), ('under_review', 'قيد المراجعة'), ('confirmed', 'مؤكد'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي'), ('expired', 'منتهي')], default='payment_pending', max_length=20, verbose_name='الحالة')),
                ('payment_reference', models.CharField(blank=True, max_length=120, verbose_name='مرجع التحويل')),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='payments/', verbose_name='إثبات الدفع')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت رفع الإثبات')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت التأكيد')),
                ('rejection_reason', models.CharField(blank=True, max_length=255, verbose_name='سبب الرفض')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config_app.paymentmethod', verbose_name='وسيلة الدفع')),
                ('pickup_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='config_app.pickuppoint', verbose_name='نقطة الالتقاط')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='config_app.route', verbose_name='المسار')),
            ],
            options={
                'verbose_name': 'اشتراك / حجز',
                'verbose_name_plural': 'الاشتراكات والحجوزات',
                'ordering': ['-created_at'],
            },
        ),
    ]
