# Generated by Django 5.2 on 2026-08-31 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
        ('config_app', '0006_pickuptime'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='morning_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='config_app.morningslot', verbose_name='موعد الذهاب'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='return_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='config_app.returnslot', verbose_name='موعد العودة'),
        ),
    ]
