# Generated by Django 5.2 on 2026-08-18 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='شركة النقل والرحلات', max_length=150, verbose_name='اسم الشركة')),
                ('tagline', models.CharField(blank=True, max_length=200, verbose_name='الشعار النصي')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='الهاتف')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='الشعار')),
            ],
            options={
                'verbose_name': 'إعدادات الشركة',
                'verbose_name_plural': 'إعدادات الشركة',
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='الكود')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='الاسم بالإنجليزية')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'وجهة',
                'verbose_name_plural': 'الوجهات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MorningSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='الكود')),
                ('departure_time', models.TimeField(verbose_name='وقت الانطلاق')),
                ('name', models.CharField(max_length=60, verbose_name='الاسم')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'موعد ذهاب',
                'verbose_name_plural': 'مواعيد الذهاب',
                'ordering': ['departure_time'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='الكود')),
                ('name', models.CharField(max_length=60, verbose_name='الاسم')),
                ('name_en', models.CharField(blank=True, max_length=60, verbose_name='الاسم بالإنجليزية')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'وسيلة دفع',
                'verbose_name_plural': 'وسائل الدفع',
            },
        ),
        migrations.CreateModel(
            name='ReturnSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='الكود')),
                ('departure_time', models.TimeField(verbose_name='وقت العودة')),
                ('name', models.CharField(max_length=60, verbose_name='الاسم')),
                ('capacity', models.PositiveIntegerField(default=50, verbose_name='السعة')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'موعد عودة',
                'verbose_name_plural': 'مواعيد العودة',
                'ordering': ['departure_time'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_name', models.CharField(max_length=120, verbose_name='اسم صاحب الحساب')),
                ('number', models.CharField(max_length=60, verbose_name='رقم الحساب / المحفظة')),
                ('instructions', models.TextField(blank=True, verbose_name='تعليمات')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='config_app.paymentmethod', verbose_name='الوسيلة')),
            ],
            options={
                'verbose_name': 'حساب استلام',
                'verbose_name_plural': 'حسابات الاستلام',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='الكود')),
                ('origin_label', models.CharField(max_length=150, verbose_name='خط الانطلاق')),
                ('name', models.CharField(max_length=180, verbose_name='اسم المسار')),
                ('name_en', models.CharField(blank=True, max_length=180, verbose_name='الاسم بالإنجليزية')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='config_app.destination', verbose_name='الوجهة')),
            ],
            options={
                'verbose_name': 'مسار',
                'verbose_name_plural': 'المسارات',
                'ordering': ['origin_label', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('term', 'ترم'), ('monthly', 'شهري'), ('daily', 'يومي')], max_length=10, verbose_name='نوع الاشتراك')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('effective_date', models.DateField(verbose_name='تاريخ السريان')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='config_app.route', verbose_name='المسار')),
            ],
            options={
                'verbose_name': 'قاعدة تسعير',
                'verbose_name_plural': 'قواعد التسعير',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='PickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم نقطة الالتقاط')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='الموقع')),
                ('sequence', models.PositiveIntegerField(default=1, verbose_name='الترتيب')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_points', to='config_app.route', verbose_name='المسار')),
            ],
            options={
                'verbose_name': 'نقطة التقاط',
                'verbose_name_plural': 'نقاط الالتقاط',
                'ordering': ['route', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الجامعة')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='الاسم بالإنجليزية')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='universities', to='config_app.destination', verbose_name='الوجهة')),
            ],
            options={
                'verbose_name': 'جامعة',
                'verbose_name_plural': 'الجامعات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SeatCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_seats', models.PositiveIntegerField(default=50, verbose_name='إجمالي المقاعد')),
                ('morning_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacities', to='config_app.morningslot', verbose_name='الموعد')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacities', to='config_app.route', verbose_name='المسار')),
            ],
            options={
                'verbose_name': 'سعة مقاعد',
                'verbose_name_plural': 'سعات المقاعد',
                'unique_together': {('route', 'morning_slot')},
            },
        ),
    ]
