# Generated by Django 5.2 on 2026-08-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatcapacity',
            name='layout',
            field=models.CharField(choices=[('bus50', 'أتوبيس (٥٠ راكب)'), ('hiace15', 'هاي إيس (١٥ راكب)')], default='bus50', max_length=12, verbose_name='نوع المركبة'),
        ),
        migrations.AlterField(
            model_name='seatcapacity',
            name='total_seats',
            field=models.PositiveIntegerField(default=49, verbose_name='إجمالي المقاعد'),
        ),
    ]
