# Generated by Django 5.2 on 2026-08-22 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0002_seatcapacity_layout_alter_seatcapacity_total_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatcapacity',
            name='booking_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='تعليمات الحجز'),
        ),
        migrations.AddField(
            model_name='seatcapacity',
            name='female_seats',
            field=models.CharField(blank=True, help_text='أرقام المقاعد المخصصة للإناث مفصولة بفاصلة، مثال: 1,2,7,8', max_length=255, verbose_name='مقاعد الإناث'),
        ),
        migrations.AddField(
            model_name='seatcapacity',
            name='male_seats',
            field=models.CharField(blank=True, help_text='أرقام المقاعد المخصصة للذكور مفصولة بفاصلة', max_length=255, verbose_name='مقاعد الذكور'),
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الكلية')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colleges', to='config_app.university', verbose_name='الجامعة')),
            ],
            options={
                'verbose_name': 'كلية',
                'verbose_name_plural': 'الكليات',
                'ordering': ['university', 'name'],
            },
        ),
    ]
