# Generated by Django 5.2 on 2026-08-30 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0003_seatcapacity_booking_note_seatcapacity_female_seats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuppoint',
            name='center',
            field=models.CharField(blank=True, choices=[('shebin', 'شبين الكوم'), ('quesna', 'قويسنا'), ('bagour', 'الباجور'), ('benha', 'بنها')], max_length=10, verbose_name='المركز'),
        ),
    ]
