# Generated by Django 5.2 on 2026-08-31 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0004_pickuppoint_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='seat_selection_enabled',
            field=models.BooleanField(default=True, help_text='عند التفعيل يختار الطالب مقعده من الرسم؛ وإلا يُخصَّص له مقعد تلقائياً.', verbose_name='إظهار خريطة اختيار المقاعد للطالب'),
        ),
    ]
