# Generated by Django 5.2 on 2026-08-31 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0005_route_seat_selection_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('go', 'ذهاب'), ('return', 'عودة')], max_length=6, verbose_name='الاتجاه')),
                ('time', models.TimeField(verbose_name='الوقت')),
                ('morning_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickup_times', to='config_app.morningslot', verbose_name='رحلة الذهاب')),
                ('pickup_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='config_app.pickuppoint', verbose_name='نقطة الالتقاط')),
                ('return_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pickup_times', to='config_app.returnslot', verbose_name='رحلة العودة')),
            ],
            options={
                'verbose_name': 'موعد نقطة',
                'verbose_name_plural': 'مواعيد النقاط',
                'ordering': ['time'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('direction', 'go')), fields=('pickup_point', 'morning_slot'), name='uniq_go_pickup_time'), models.UniqueConstraint(condition=models.Q(('direction', 'return')), fields=('pickup_point', 'return_slot'), name='uniq_return_pickup_time')],
            },
        ),
    ]
