# Generated by Django 5.2 on 2026-09-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0008_booking_toggles_and_daily_pricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleScreenPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20, verbose_name='الدور')),
                ('screen', models.CharField(max_length=40, verbose_name='الشاشة')),
                ('can_view', models.BooleanField(default=False, verbose_name='عرض')),
                ('can_add', models.BooleanField(default=False, verbose_name='إضافة')),
                ('can_edit', models.BooleanField(default=False, verbose_name='تعديل')),
                ('can_delete', models.BooleanField(default=False, verbose_name='حذف')),
            ],
            options={
                'verbose_name': 'صلاحية دور',
                'verbose_name_plural': 'صلاحيات الأدوار',
                'unique_together': {('role', 'screen')},
            },
        ),
    ]
