# Generated by Django 5.2 on 2026-09-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0009_rolescreenpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='daily_booking_cutoff_time',
            field=models.TimeField(blank=True, help_text='بعد هذا الوقت يُغلق الحجز اليومي تلقائياً حتى منتصف الليل، ثم يُفتح تلقائياً. اتركه فارغاً لتعطيل الإغلاق التلقائي بالوقت (يبقى الإغلاق اليدوي فقط).', null=True, verbose_name='وقت إغلاق الحجز اليومي تلقائياً'),
        ),
    ]
