# Generated by Django 5.2 on 2026-09-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0010_companysettings_daily_booking_cutoff_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='attendance_lock_time',
            field=models.TimeField(blank=True, help_text='بعد هذا الوقت يُقفل تأكيد/اعتذار حضور رحلة الغد لمشتركي الترم والشهري؛ من لم يؤكد حضوره صراحةً يُعتبر غائباً لهذا اليوم فقط ويُحرَّر مقعده، ثم يُشغَّل التخصيص تلقائياً لتوزيع المقاعد المحررة على قائمة انتظار اليومي. اتركه فارغاً لتعطيل هذا الإجراء التلقائي.', null=True, verbose_name='وقت قفل تأكيدات حضور الترم/الشهري وتشغيل التخصيص تلقائياً'),
        ),
    ]
