# Generated by Django 5.2 on 2026-09-19 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0011_companysettings_attendance_lock_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='return_destination',
            field=models.ForeignKey(blank=True, help_text='اتركها فارغة لو العودة بترجع لنفس نقطة انطلاق الذهاب — عبّيها بس لو خط العودة بينتهي في مدينة مختلفة.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_routes', to='config_app.destination', verbose_name='الوجهة عند العودة (اختياري)'),
        ),
        migrations.AlterField(
            model_name='route',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='config_app.destination', verbose_name='الوجهة (ذهاب)'),
        ),
    ]
