# Generated by Django 5.2 on 2026-08-18 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='العنوان')),
                ('message', models.CharField(blank=True, max_length=400, verbose_name='الرسالة')),
                ('link', models.CharField(blank=True, max_length=200, verbose_name='الرابط')),
                ('severity', models.CharField(choices=[('info', 'معلومة'), ('success', 'نجاح'), ('warning', 'تنبيه'), ('error', 'خطأ')], default='info', max_length=10, verbose_name='النوع')),
                ('read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
    ]
