# Generated by Django 5.2 on 2026-08-22 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0003_seatcapacity_booking_note_seatcapacity_female_seats_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='academic_year',
            field=models.CharField(blank=True, choices=[('1', 'الفرقة الأولى'), ('2', 'الفرقة الثانية'), ('3', 'الفرقة الثالثة'), ('4', 'الفرقة الرابعة'), ('5', 'الفرقة الخامسة')], max_length=1, verbose_name='الفرقة الدراسية'),
        ),
        migrations.AddField(
            model_name='user',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='config_app.college', verbose_name='الكلية'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=6, verbose_name='النوع'),
        ),
    ]
