# Generated by Django 5.2 on 2026-08-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_academic_year_user_college_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'مدير عام'), ('transport_manager', 'مدير النقل'), ('payment_officer', 'مسؤول المدفوعات'), ('operations', 'مشرف التشغيل'), ('bus_supervisor', 'مشرف الأسطول'), ('tourism_manager', 'مدير السياحة'), ('driver', 'سائق'), ('student', 'طالب')], default='student', max_length=20, verbose_name='الدور'),
        ),
    ]
