# Generated by Django 5.2 on 2026-08-30 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='center',
            field=models.CharField(blank=True, choices=[('shebin', 'شبين الكوم'), ('quesna', 'قويسنا'), ('bagour', 'الباجور'), ('benha', 'بنها')], max_length=10, verbose_name='المركز التابع له'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='تفاصيل العنوان'),
        ),
    ]
