# Generated by Django 5.2 on 2026-08-30 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0004_pickuppoint_center'),
        ('users', '0004_user_center_alter_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pickup_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_students', to='config_app.pickuppoint', verbose_name='نقطة الالتقاط'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='تفاصيل إضافية'),
        ),
    ]
