# Generated by Django 5.2 on 2026-08-18 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_type', models.CharField(default='daily', max_length=10, verbose_name='نوع الأولوية')),
                ('status', models.CharField(choices=[('waiting', 'قائمة انتظار'), ('confirmed', 'مؤكد'), ('cancelled', 'ملغي')], default='waiting', max_length=12, verbose_name='الحالة')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الطلب')),
                ('queue_position', models.PositiveIntegerField(blank=True, null=True, verbose_name='ترتيب الطابور')),
            ],
            options={
                'verbose_name': 'طلب مقعد',
                'verbose_name_plural': 'طلبات المقاعد',
                'ordering': ['requested_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('total_seats', models.PositiveIntegerField(default=50, verbose_name='إجمالي المقاعد')),
                ('allocated_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت التخصيص')),
                ('morning_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_trips', to='config_app.morningslot', verbose_name='الموعد')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_trips', to='config_app.route', verbose_name='المسار')),
            ],
            options={
                'verbose_name': 'رحلة يومية',
                'verbose_name_plural': 'الرحلات اليومية',
                'ordering': ['date', 'morning_slot', 'route'],
            },
        ),
        migrations.CreateModel(
            name='ReturnBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('status', models.CharField(choices=[('confirmed', 'مؤكد'), ('cancelled', 'ملغي')], default='confirmed', max_length=12, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('return_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='config_app.returnslot', verbose_name='موعد العودة')),
            ],
            options={
                'verbose_name': 'حجز عودة',
                'verbose_name_plural': 'حجوزات العودة',
                'ordering': ['date', 'return_slot'],
            },
        ),
    ]
