# Generated by Django 5.2 on 2026-08-18 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        ('config_app', '0001_initial'),
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='returnbooking',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_bookings', to=settings.AUTH_USER_MODEL, verbose_name='الطالب'),
        ),
        migrations.AddField(
            model_name='returnbooking',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_bookings', to='config_app.university', verbose_name='الجامعة'),
        ),
        migrations.AddField(
            model_name='seatrequest',
            name='daily_trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_requests', to='operations.dailytrip', verbose_name='الرحلة'),
        ),
        migrations.AddField(
            model_name='seatrequest',
            name='pickup_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat_requests', to='config_app.pickuppoint', verbose_name='نقطة الالتقاط'),
        ),
        migrations.AddField(
            model_name='seatrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_requests', to=settings.AUTH_USER_MODEL, verbose_name='الطالب'),
        ),
        migrations.AddField(
            model_name='seatrequest',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat_requests', to='bookings.subscription', verbose_name='الاشتراك'),
        ),
        migrations.AddField(
            model_name='seatrequest',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seat_requests', to='config_app.university', verbose_name='الجامعة'),
        ),
        migrations.AlterUniqueTogether(
            name='dailytrip',
            unique_together={('date', 'route', 'morning_slot')},
        ),
        migrations.AlterUniqueTogether(
            name='seatrequest',
            unique_together={('daily_trip', 'student')},
        ),
    ]
