# Generated by Django 5.2 on 2026-08-18 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
        ('config_app', '0002_seatcapacity_layout_alter_seatcapacity_total_seats'),
        ('operations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytrip',
            name='layout',
            field=models.CharField(default='bus50', max_length=12, verbose_name='نوع المركبة'),
        ),
        migrations.AddField(
            model_name='seatrequest',
            name='qr_token',
            field=models.CharField(blank=True, max_length=40, verbose_name='رمز التذكرة'),
        ),
        migrations.AddField(
            model_name='seatrequest',
            name='seat_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='رقم المقعد'),
        ),
        migrations.AlterField(
            model_name='dailytrip',
            name='total_seats',
            field=models.PositiveIntegerField(default=49, verbose_name='إجمالي المقاعد'),
        ),
        migrations.AlterField(
            model_name='seatrequest',
            name='status',
            field=models.CharField(choices=[('waiting', 'قائمة انتظار'), ('held', 'معلق (بانتظار الدفع)'), ('confirmed', 'مؤكد'), ('cancelled', 'ملغي')], default='waiting', max_length=12, verbose_name='الحالة'),
        ),
        migrations.CreateModel(
            name='TermSeatLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveIntegerField(verbose_name='رقم المقعد')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('morning_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config_app.morningslot', verbose_name='الموعد')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config_app.route', verbose_name='المسار')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_seats', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_seats', to='bookings.subscription', verbose_name='الاشتراك')),
            ],
            options={
                'verbose_name': 'مقعد ترم مقفول',
                'verbose_name_plural': 'مقاعد الترم المقفولة',
            },
        ),
        migrations.CreateModel(
            name='SeatAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
                ('term_lock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='operations.termseatlock', verbose_name='مقعد الترم')),
            ],
            options={
                'verbose_name': 'غياب مقعد',
                'verbose_name_plural': 'غيابات المقاعد',
            },
        ),
        migrations.AddConstraint(
            model_name='termseatlock',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('route', 'morning_slot', 'seat_number'), name='uniq_active_term_seat'),
        ),
        migrations.AlterUniqueTogether(
            name='seatabsence',
            unique_together={('term_lock', 'date')},
        ),
    ]
