# Generated by Django 5.2 on 2026-08-23 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0003_seatcapacity_booking_note_seatcapacity_female_seats_and_more'),
        ('operations', '0003_dailytrip_layout_seatrequest_qr_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnbooking',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_bookings', to='config_app.route', verbose_name='المسار'),
        ),
    ]
