# Generated by Django 5.2 on 2026-08-31 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0004_pickuppoint_center'),
        ('operations', '0004_returnbooking_route'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailytrip',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailytrip',
            name='direction',
            field=models.CharField(choices=[('go', 'ذهاب'), ('return', 'عودة')], default='go', max_length=6, verbose_name='الاتجاه'),
        ),
        migrations.AddField(
            model_name='dailytrip',
            name='return_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_trips', to='config_app.returnslot', verbose_name='موعد العودة'),
        ),
        migrations.AlterField(
            model_name='dailytrip',
            name='morning_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_trips', to='config_app.morningslot', verbose_name='موعد الذهاب'),
        ),
        migrations.AddConstraint(
            model_name='dailytrip',
            constraint=models.UniqueConstraint(condition=models.Q(('direction', 'go')), fields=('date', 'route', 'morning_slot'), name='uniq_go_trip'),
        ),
        migrations.AddConstraint(
            model_name='dailytrip',
            constraint=models.UniqueConstraint(condition=models.Q(('direction', 'return')), fields=('date', 'route', 'return_slot'), name='uniq_return_trip'),
        ),
    ]
