# Generated by Django 5.2 on 2026-08-31 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
        ('config_app', '0004_pickuppoint_center'),
        ('operations', '0005_alter_dailytrip_unique_together_dailytrip_direction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='termseatlock',
            options={'verbose_name': 'مقعد مشترك مقفول', 'verbose_name_plural': 'مقاعد المشتركين المقفولة'},
        ),
        migrations.RemoveConstraint(
            model_name='termseatlock',
            name='uniq_active_term_seat',
        ),
        migrations.AddField(
            model_name='termseatlock',
            name='direction',
            field=models.CharField(choices=[('go', 'ذهاب'), ('return', 'عودة')], default='go', max_length=6, verbose_name='الاتجاه'),
        ),
        migrations.AddField(
            model_name='termseatlock',
            name='return_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term_seats', to='config_app.returnslot', verbose_name='موعد العودة'),
        ),
        migrations.AlterField(
            model_name='termseatlock',
            name='morning_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config_app.morningslot', verbose_name='موعد الذهاب'),
        ),
        migrations.AddConstraint(
            model_name='termseatlock',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True), ('direction', 'go')), fields=('route', 'morning_slot', 'seat_number'), name='uniq_active_term_seat'),
        ),
        migrations.AddConstraint(
            model_name='termseatlock',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True), ('direction', 'return')), fields=('route', 'return_slot', 'seat_number'), name='uniq_active_return_term_seat'),
        ),
    ]
