# Generated by Django 5.2 on 2026-08-31 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0006_pickuptime'),
        ('operations', '0006_alter_termseatlock_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySlotChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('morning_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config_app.morningslot', verbose_name='موعد الذهاب')),
                ('return_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config_app.returnslot', verbose_name='موعد العودة')),
                ('term_lock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_choices', to='operations.termseatlock', verbose_name='المقعد الثابت')),
            ],
            options={
                'verbose_name': 'اختيار سلوت يومي',
                'verbose_name_plural': 'اختيارات السلوت اليومية',
                'unique_together': {('term_lock', 'date')},
            },
        ),
    ]
