# Generated by Django 5.2 on 2026-09-18 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_dailyslotchoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('term_lock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='operations.termseatlock', verbose_name='مقعد الترم')),
            ],
            options={
                'verbose_name': 'تأكيد حضور',
                'verbose_name_plural': 'تأكيدات الحضور',
                'unique_together': {('term_lock', 'date')},
            },
        ),
    ]
