# Generated by Django 5.2 on 2026-09-18 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_subscription_whatsapp_notified_at'),
        ('operations', '0008_attendanceconfirmation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReschedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت التأجيل')),
                ('new_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='operations.dailytrip', verbose_name='الرحلة الجديدة')),
                ('old_trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='operations.dailytrip', verbose_name='الرحلة القديمة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reschedules', to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedules', to='bookings.subscription', verbose_name='الاشتراك')),
            ],
            options={
                'verbose_name': 'تأجيل حجز يومي',
                'verbose_name_plural': 'تأجيلات الحجز اليومي',
                'ordering': ['-created_at'],
            },
        ),
    ]
