# Generated by Django 5.2 on 2026-08-18 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('validity_date', models.DateField(blank=True, null=True, verbose_name='صالح حتى')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات / شروط')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('sent', 'مُرسل للعميل'), ('accepted', 'مقبول'), ('rejected', 'مرفوض'), ('expired', 'منتهي')], default='draft', max_length=10, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'عرض سعر',
                'verbose_name_plural': 'عروض الأسعار',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourismRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='الاسم الكامل')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('national_id', models.CharField(blank=True, max_length=20, verbose_name='الرقم القومي')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
                ('origin', models.CharField(max_length=150, verbose_name='من')),
                ('destination', models.CharField(max_length=150, verbose_name='إلى')),
                ('travel_date', models.DateField(verbose_name='تاريخ الرحلة')),
                ('travelers', models.PositiveIntegerField(default=1, verbose_name='عدد المسافرين')),
                ('trip_type', models.CharField(choices=[('seat', 'فردي / بالمقعد'), ('private', 'رحلة خاصة / مركبة كاملة')], default='private', max_length=10, verbose_name='نوع الرحلة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('status', models.CharField(choices=[('pending', 'بانتظار المراجعة'), ('quoted', 'تم إرسال عرض سعر'), ('accepted', 'مقبول'), ('rejected', 'مرفوض'), ('expired', 'منتهي')], default='pending', max_length=10, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'طلب سياحة',
                'verbose_name_plural': 'طلبات السياحة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='نوع المركبة')),
                ('name_en', models.CharField(blank=True, max_length=80, verbose_name='الاسم بالإنجليزية')),
                ('capacity', models.PositiveIntegerField(default=14, verbose_name='السعة')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'نوع مركبة',
                'verbose_name_plural': 'أنواع المركبات',
            },
        ),
    ]
