# Generated by Django 5.2 on 2026-08-23 18:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config_app', '0003_seatcapacity_booking_note_seatcapacity_female_seats_and_more'),
        ('operations', '0003_dailytrip_layout_seatrequest_qr_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='رقم اللوحة')),
                ('license_number', models.CharField(blank=True, max_length=40, verbose_name='رقم الرخصة')),
                ('vehicle_type', models.CharField(blank=True, max_length=40, verbose_name='نوع المركبة')),
                ('brand', models.CharField(blank=True, max_length=40, verbose_name='الماركة')),
                ('model', models.CharField(blank=True, max_length=40, verbose_name='الموديل')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='سنة الصنع')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='السعة')),
                ('license_expiry', models.DateField(blank=True, null=True, verbose_name='انتهاء رخصة المركبة')),
                ('status', models.CharField(choices=[('available', 'متاحة'), ('in_trip', 'في رحلة'), ('maintenance', 'في الصيانة'), ('out_of_service', 'خارج الخدمة'), ('inactive', 'غير نشطة')], default='available', max_length=16, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مركبة',
                'verbose_name_plural': 'المركبات',
                'ordering': ['plate_number'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40, verbose_name='العملية')),
                ('entity', models.CharField(max_length=60, verbose_name='الكيان')),
                ('entity_id', models.CharField(blank=True, max_length=40, verbose_name='معرّف الكيان')),
                ('summary', models.CharField(blank=True, max_length=255, verbose_name='الوصف')),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل تدقيق',
                'verbose_name_plural': 'سجلات التدقيق',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='الاسم')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('license_number', models.CharField(blank=True, max_length=40, verbose_name='رقم الرخصة')),
                ('license_type', models.CharField(blank=True, choices=[('first', 'أولى'), ('second', 'ثانية'), ('third', 'ثالثة'), ('private', 'خاصة')], max_length=10, verbose_name='نوع الرخصة')),
                ('license_expiry', models.DateField(blank=True, null=True, verbose_name='انتهاء الرخصة')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط'), ('suspended', 'موقوف')], default='active', max_length=12, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_profile', to=settings.AUTH_USER_MODEL, verbose_name='حساب الدخول')),
            ],
            options={
                'verbose_name': 'سائق',
                'verbose_name_plural': 'السائقون',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='TrafficFine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='التاريخ')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قيمة الغرامة')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='سبب الغرامة')),
                ('status', models.CharField(choices=[('unpaid', 'غير مدفوعة'), ('paid', 'مدفوعة')], default='unpaid', max_length=8, verbose_name='الحالة')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='fines/', verbose_name='المرفق')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fines', to='fleet.driver', verbose_name='السائق')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fines', to='fleet.vehicle', verbose_name='المركبة')),
            ],
            options={
                'verbose_name': 'غرامة مرورية',
                'verbose_name_plural': 'الغرامات المرورية',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='التاريخ')),
                ('is_workshop', models.BooleanField(default=False, verbose_name='ورشة')),
                ('maintenance_type', models.CharField(blank=True, max_length=80, verbose_name='نوع الصيانة/الإصلاح')),
                ('workshop_name', models.CharField(blank=True, max_length=120, verbose_name='اسم الورشة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='maintenance/', verbose_name='الفاتورة/المرفق')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_records', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance', to='fleet.vehicle', verbose_name='المركبة')),
            ],
            options={
                'verbose_name': 'صيانة / ورشة',
                'verbose_name_plural': 'الصيانة والورش',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='VehicleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='بداية الرحلة')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='نهاية الرحلة')),
                ('status', models.CharField(choices=[('planned', 'مخطط'), ('started', 'بدأت'), ('completed', 'اكتملت'), ('cancelled', 'ملغاة')], default='planned', max_length=12, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='operations.dailytrip', verbose_name='الرحلة')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='fleet.driver', verbose_name='السائق')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='config_app.route', verbose_name='المسار')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='fleet.vehicle', verbose_name='المركبة')),
            ],
            options={
                'verbose_name': 'تعيين يومي',
                'verbose_name_plural': 'التعيينات اليومية',
                'ordering': ['-date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TripExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('fuel', 'وقود'), ('tolls', 'كارتات / رسوم طرق'), ('other', 'مصروف آخر')], max_length=8, verbose_name='نوع المصروف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الكمية (لتر)')),
                ('expense_type', models.CharField(blank=True, max_length=80, verbose_name='نوع (مصروف آخر)')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='التاريخ')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='الوصف')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='expenses/', verbose_name='الإيصال')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('status', models.CharField(choices=[('pending', 'بانتظار المراجعة'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=10, verbose_name='الحالة')),
                ('review_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('rejection_reason', models.CharField(blank=True, max_length=255, verbose_name='سبب الرفض')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_expenses', to=settings.AUTH_USER_MODEL, verbose_name='سُجّلت بواسطة')),
                ('daily_trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='operations.dailytrip', verbose_name='الرحلة')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='fleet.driver', verbose_name='السائق')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_expenses', to=settings.AUTH_USER_MODEL, verbose_name='روجعت بواسطة')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='fleet.vehicle', verbose_name='المركبة')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='fleet.vehicleassignment', verbose_name='التعيين')),
            ],
            options={
                'verbose_name': 'مصروف رحلة',
                'verbose_name_plural': 'مصروفات الرحلات',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
