# Generated by Django 5.2 on 2026-09-16 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
        ('tourism', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleassignment',
            name='tourism_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='tourism.tourismrequest', verbose_name='رحلة سياحية'),
        ),
    ]
